# Site settings
title: Mohamed Salaheldeen
description: Blog of Mohamed Salaheldeen
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohamed Salaheldeen
user_description: I'm a graduate student from Egypt. I seeking to be a mathematical phystisit. 
user_title: Graduate Student
email: m_salaheldeen@outlook.com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  msalahelden
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

